import prisma from '../config/prisma';
import logger from '../config/logger';

type SlackBlock = Record<string, unknown>;

// ─── HTTP send ────────────────────────────────────────────────

export async function sendSlackMessage(webhookUrl: string, blocks: SlackBlock[]): Promise<void> {
  const res = await fetch(webhookUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ blocks }),
  });
  if (!res.ok) {
    const body = await res.text().catch(() => '');
    throw new Error(`Slack webhook ${res.status}: ${body}`);
  }
}

// ─── Helpers ──────────────────────────────────────────────────

function formatDate(d: Date): string {
  return d.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', timeZone: 'Asia/Ho_Chi_Minh' });
}

function taskLine(title: string, suffix = ''): string {
  return `• ${title}${suffix}`;
}

function daysAgo(deadline: Date, now: Date): string {
  const days = Math.floor((now.getTime() - deadline.getTime()) / 86_400_000);
  return days === 1 ? '1 day overdue' : `${days} days overdue`;
}

// ─── Daily Digest ─────────────────────────────────────────────

export async function buildDailyDigestBlocks(projectId: string, date: Date): Promise<SlackBlock[]> {
  const project = await prisma.project.findUnique({
    where: { id: projectId },
    select: { name: true },
  });
  if (!project) return [];

  const startOfDay = new Date(date);
  startOfDay.setHours(0, 0, 0, 0);
  const endOfDay = new Date(date);
  endOfDay.setHours(23, 59, 59, 999);

  const [completedToday, overdue, updated] = await Promise.all([
    prisma.task.findMany({
      where: { projectId, completedAt: { gte: startOfDay, lte: endOfDay } },
      select: { title: true },
      orderBy: { completedAt: 'desc' },
      take: 15,
    }),
    prisma.task.findMany({
      where: { projectId, deadline: { lt: date }, status: { not: 'done' } },
      select: { title: true, deadline: true },
      orderBy: { deadline: 'asc' },
      take: 10,
    }),
    prisma.task.findMany({
      where: {
        projectId,
        updatedAt: { gte: startOfDay, lte: endOfDay },
        completedAt: null,
        status: { not: 'done' },
      },
      select: { title: true, status: true },
      orderBy: { updatedAt: 'desc' },
      take: 10,
    }),
  ]);

  const blocks: SlackBlock[] = [
    { type: 'header', text: { type: 'plain_text', text: `📋 Daily Update — ${project.name} — ${formatDate(date)}`, emoji: true } },
    { type: 'divider' },
  ];

  // Completed today
  if (completedToday.length > 0) {
    blocks.push({
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*✅ Completed Today (${completedToday.length})*\n${completedToday.map((t) => taskLine(t.title)).join('\n')}`,
      },
    });
  } else {
    blocks.push({ type: 'section', text: { type: 'mrkdwn', text: '*✅ Completed Today*\n_None_' } });
  }

  blocks.push({ type: 'divider' });

  // Updated (in-progress)
  if (updated.length > 0) {
    blocks.push({
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*🔄 Updated Today (${updated.length})*\n${updated.map((t) => taskLine(t.title, ` [${t.status}]`)).join('\n')}`,
      },
    });
    blocks.push({ type: 'divider' });
  }

  // Overdue
  if (overdue.length > 0) {
    blocks.push({
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*⚠️ Overdue (${overdue.length})*\n${overdue.map((t) => taskLine(t.title, t.deadline ? ` — ${daysAgo(t.deadline, date)}` : '')).join('\n')}`,
      },
    });
  }

  blocks.push({
    type: 'context',
    elements: [{ type: 'mrkdwn', text: `Generated by MicroDo · ${formatDate(date)}` }],
  });

  return blocks;
}

// ─── Weekly Digest ────────────────────────────────────────────

export async function buildWeeklyDigestBlocks(projectId: string, weekStart: Date, weekEnd: Date): Promise<SlackBlock[]> {
  const project = await prisma.project.findUnique({
    where: { id: projectId },
    select: { name: true },
  });
  if (!project) return [];

  const [completedWeek, overdue, created] = await Promise.all([
    prisma.task.findMany({
      where: { projectId, completedAt: { gte: weekStart, lte: weekEnd } },
      select: { title: true },
      orderBy: { completedAt: 'desc' },
      take: 20,
    }),
    prisma.task.findMany({
      where: { projectId, deadline: { lt: weekEnd }, status: { not: 'done' } },
      select: { title: true, deadline: true },
      orderBy: { deadline: 'asc' },
      take: 10,
    }),
    prisma.task.findMany({
      where: { projectId, createdAt: { gte: weekStart, lte: weekEnd } },
      select: { title: true, status: true },
      orderBy: { createdAt: 'desc' },
      take: 15,
    }),
  ]);

  const period = `${formatDate(weekStart)} – ${formatDate(weekEnd)}`;

  const blocks: SlackBlock[] = [
    { type: 'header', text: { type: 'plain_text', text: `📊 Weekly Summary — ${project.name}`, emoji: true } },
    { type: 'section', text: { type: 'mrkdwn', text: `*Period:* ${period}` } },
    { type: 'divider' },
  ];

  // Completed
  blocks.push({
    type: 'section',
    text: {
      type: 'mrkdwn',
      text: completedWeek.length > 0
        ? `*✅ Completed This Week (${completedWeek.length})*\n${completedWeek.map((t) => taskLine(t.title)).join('\n')}`
        : '*✅ Completed This Week*\n_None_',
    },
  });

  blocks.push({ type: 'divider' });

  // New tasks
  if (created.length > 0) {
    blocks.push({
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*🆕 New Tasks This Week (${created.length})*\n${created.map((t) => taskLine(t.title, ` [${t.status}]`)).join('\n')}`,
      },
    });
    blocks.push({ type: 'divider' });
  }

  // Overdue
  if (overdue.length > 0) {
    blocks.push({
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*⚠️ Overdue (${overdue.length})*\n${overdue.map((t) => taskLine(t.title, t.deadline ? ` — ${daysAgo(t.deadline, weekEnd)}` : '')).join('\n')}`,
      },
    });
  }

  blocks.push({
    type: 'context',
    elements: [{ type: 'mrkdwn', text: `Generated by MicroDo · Weekly report` }],
  });

  return blocks;
}
