-- Rename NotificationType enum values to match plan naming convention
ALTER TYPE "NotificationType" RENAME VALUE 'TASK_DEADLINE_3D'  TO 'DEADLINE_3_DAYS';
ALTER TYPE "NotificationType" RENAME VALUE 'TASK_DEADLINE_2D'  TO 'DEADLINE_2_DAYS';
ALTER TYPE "NotificationType" RENAME VALUE 'TASK_DEADLINE_1D'  TO 'DEADLINE_1_DAY';
ALTER TYPE "NotificationType" RENAME VALUE 'TASK_DEADLINE_12H' TO 'DEADLINE_12_HOURS';
ALTER TYPE "NotificationType" RENAME VALUE 'TASK_DEADLINE_4H'  TO 'DEADLINE_4_HOURS';
ALTER TYPE "NotificationType" RENAME VALUE 'TASK_DEADLINE_1H'  TO 'DEADLINE_1_HOUR';
